### PR TITLE
Add piqa dataset benchmark

### PR DESCRIPTION
**Pull request by gururise**
First attempt to add the [PIQA dataset ](https://huggingface.co/datasets/piqa) (validation split) to benchmark suite.

### CODE REVIEW

**Comment by gururise** [comment]
Don't know if I have an optimal prompt, but here's the initial results:

dataset | model | Squad "Mini" (f1) | Piqa (acc)
------- | ----- | ------ |-----
Original Alpaca | samwit/alpaca7B-lora | 34.63 | 50.5
Cleaned Alpaca (Mar 27) | tloen/alpaca-lora-7b | 49.64 | 54.0

**Comment by HideLord** [comment]
Isn't the random performance around 50 since there are only two answers?

**Comment by gururise** [comment]
> Isn't the random performance around 50 since there are only two answers?

Yes. Random is 50%. Leaderboard [here](https://yonatanbisk.com/piqa/).

Seems "Majority Class" Performance on this benchmark is 50.4%

**Review by gururise — COMMENTED** [review]
Updated the scoring of the Squad benchmark.

**Pull request merged**
